// ==UserScript==
// @name         乐造：Webex UT比较
// @icon         https://tairraos.github.io/tamperMonkey/lemade.ico
// @namespace    http://tampermonkey.net/
// @version      0.2
// @description  小乐开发专用，Webex UT比较工具
// @author       Xiaole Tao
// @include      http://*/job/Thinclient-JS-UT-EC-MASTER/
// @grant        none
// @require      http://code.jquery.com/jquery-2.2.4.min.js
// @updateURL    https://tairraos.github.io/tamperMonkey/WebexUTTool.js
// @downloadURL  https://tairraos.github.io/tamperMonkey/WebexUTTool.js
// @run-at       document-end
// ==/UserScript==

(function(b){var a=window.leSmartTool={baseURL:location.protocol+"//"+location.host+location.pathname.replace(/UT-Parallel\/.*/,"UT-Parallel/"),mode:"\u663e\u793a\u5168\u90e8",filePool:[],dataPool:{},sourceData:{},targetData:{},sourceVersion:0,targetVersion:0,$form:null,$span:null,$sourceVer:null,$targetVer:null,$button:null,$meta:null,$mode:null,$table:null,run:function(){a.getVersion();a.$form=b('<div id="coverageForm"></div>').on("keydown",function(b){13===b.keyCode&&a.$button.click()});a.$span=
b("<span>\u751f\u6210\u5bf9\u6bd4\u62a5\u544a: </span>").appendTo(a.$form);a.$form.append("<span> </span>");a.$sourceVer=b('<input id="sourceVer" style="width: 50px;text-align: center;" />').appendTo(a.$form).val(a.sourceVersion);b("<button>+</button>").appendTo(a.$form).on("click",function(){a.$sourceVer.val(+a.$sourceVer.val()+1)});b("<button>-</button>").appendTo(a.$form).on("click",function(){a.$sourceVer.val(+a.$sourceVer.val()-1)});b("<span> \u5bf9\u6bd4 </span>").appendTo(a.$form);a.$targetVer=
b('<input id="targetVer" style="width: 50px;text-align: center;" />').appendTo(a.$form).val(a.targetVersion);b("<button>+</button>").appendTo(a.$form).on("click",function(){a.$targetVer.val(+a.$targetVer.val()+1)});b("<button>-</button>").appendTo(a.$form).on("click",function(){a.$targetVer.val(+a.$targetVer.val()-1)});b("<span> &nbsp; </span>").appendTo(a.$form);a.$button=b("<button>\u5f00\u59cb\u751f\u6210</button>").on("click",a.startAnalytic).appendTo(a.$form);a.$meta=b('<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />').appendTo("head");
b("#description").empty().append(a.$form)},getVersion:function(){var d=b("#buildHistory .build-row:not(.transitive)"),e;a.sourceVersion=d.eq(0).text().replace(/[^#\d\s]/g,"").replace(/^#(\d+) .*$/,"$1");for(var c=1;c<d.length-1;c++)if((e=d.eq(c).find("img").attr("alt"))&&"Success"===e.replace(/^(\w+) .*$/,"$1")){a.targetVersion=d.eq(c).text().replace(/[^#\d\s]/g,"").replace(/^#(\d+) .*$/,"$1");break}a.targetVersion||(a.targetVersion=d.eq(1).text().replace(/[^#\d\s]/g,"").replace(/^#(\d+) .*$/,"$1"))},
startAnalytic:function(){if(!a.checkNumber())return a.$span.text("\u7248\u672c\u53f7\u5fc5\u987b\u4e3a\u6570\u5b57").css("color","red");if(a.$sourceVer.val()>a.$targetVer.val()){var d=a.$targetVer.val();a.$targetVer.val(a.$sourceVer.val());a.$sourceVer.val(d)}a.analyticURL(a.baseURL+a.$sourceVer.val()+"/cobertura/",a.sourceData);a.analyticURL(a.baseURL+a.$targetVer.val()+"/cobertura/",a.targetData);b.each(b.extend({},a.sourceData,a.targetData),function(d){return-1===b.inArray(d,a.filePool)&&a.filePool.push(d)});
return a.genReport(a.filePool.sort())&&a.showReport()},genReport:function(d){var e,c=new Date,c="\u62a5\u8868\u751f\u6210\u65f6\u95f4\uff1a"+(c.getFullYear()+"/"+(c.getMonth()+1)+"/"+(c.getDate()+1)+" "+c.getHours()+":"+c.getMinutes());a.title=document.title="Build "+b("#targetVer").val()+" vs Build "+b("#sourceVer").val();a.$mode=b('<span class="change">'+a.mode+"</span>");a.$table=b('<table id="report"><tr><td>\u6587\u4ef6\u8def\u5f84</td><td>\u6761\u4ef6\u8986\u76d6\u7387</td><td>\u6761\u4ef6\u8986\u76d6\u6570</td><td>\u884c\u8986\u76d6\u7387</td><td>\u884c\u8986\u76d6\u6570</td></tr></table>');
a.$table.prepend(b("<tr></tr>").append(b('<td colspan="5">'+a.title+","+c+" \u62a5\u8868\u65b9\u5f0f\uff1a</td>").append(a.$mode)));return b.each(d,function(b,d){b=a.sourceData[d];var c=a.targetData[d],h,f;b?c||(c={conditionalsRate:0,linesRate:0,conditionsText:"",linesText:""}):b={conditionalsRate:0,linesRate:0,conditionsText:"",linesText:""};b.conditionalsRate===c.conditionalsRate&&b.linesRate===c.linesRate?a.$table.append('<tr class="same" style="background:#ffffff"><td><a href="'+c.link+'" target="_blank">'+
d+"</a></td><td>"+b.conditionalsRate+"%</td><td>"+b.conditionsText+"</td><td>"+b.linesRate+"%</td><td>"+b.linesText+"</td></tr>"):(h=(c.conditionalsRate-b.conditionalsRate).toFixed(2),f=(c.linesRate-b.linesRate).toFixed(2),e=""===b.linesText||""===c.linesText?"ffc3c3":0>h||0>f?"ffe3e3":"e3ffe3",a.$table.append('<tr class="diff1" style="background:#'+e+'"><td rowspan="2"><a href="'+b.link+'" target="_blank">'+d+"</a></td><td>"+b.conditionalsRate+"%</td><td>"+b.conditionsText+"</td><td>"+b.linesRate+
"%</td><td>"+b.linesText+"</td></tr>"),a.$table.append('<tr class="diff2" style="background:#'+e+'"><td>'+c.conditionalsRate+"% ("+(0<h?"+":"")+h+"%)</td><td>"+c.conditionsText+"</td><td>"+c.linesRate+"% ("+(0<f?"+":"")+f+"%)</td><td>"+c.linesText+"</td></tr>"))})},showReport:function(){var d=b("<style />");d.append("#report { border: 1px solid #999; border-collapse: collapse; }");d.append("#report td { padding: 2px 6px; border: 1px solid #bbb; font: 13px/13px verdana; }");d.append("#report tr.diff1 td { border-top: 2px solid #000; }");
d.append("#report tr.diff2 td, #report tr.diff1 td:first-child { border-bottom: 2px solid #000; }");d.append("#report .change, #report a { cursor: pointer; color: navy; text-decoration: blink;}");b("body").empty().append(a.$table);b("script").add("link").remove();b("head").append(d);a.$mode.on("click",function(){a.$table.css("border-collapse","separate");b(".same",a.$table).toggle();a.$table.css("border-collapse","collapse");a.$mode.text(a.mode="\u663e\u793a\u5168\u90e8"===a.mode?"\u53ea\u663e\u793a\u5dee\u5f02":
"\u663e\u793a\u5168\u90e8")})},checkNumber:function(){return/^\d+$/.test(a.$sourceVer.val())&&/^\d+$/.test(a.$targetVer.val())},analyticURL:function(b,e){b=[b];do a.analyticContent(b.shift(),b,e);while(b.length)},getPathContent:function(a,e){var c=b();e=e||"table.sortable>tbody";b.ajax({type:"GET",url:a,async:!1,dataType:"html",success:function(a){c=b(a)}});return b(e,c)},analyticContent:function(d,e,c){b(">tr",a.getPathContent(d)).each(function(){var a=b(this).find(">td"),g=a.eq(0).find("a");if(g.length)if(g.text().match(/\.js$/)){var k=
a.eq(2),a=a.eq(3),l=+a.attr("data"),f=+k.attr("data");c[g.text()]={link:d+g.attr("href"),conditionalsRate:100>=l?l:0,linesRate:100>=f?f:0,conditionsText:a.find("span.text").text(),linesText:k.find("span.text").text()}}else e.push(d+g.attr("href"))})}};a.run()})(jQuery,jQuery.noConflict());